#IMAGEN MODELO
FROM eclipse-temurin:17-jdk

#INFORMAR EL PUERTO DONDE SE EJECUTA EL CONTENEDOR(INFORMATIVO)
EXPOSE 8080

#DEFINIR DIRECTORIO RAIZ DE NUESTRO CONTENEDOR
WORKDIR /root

#COPIAR Y PEGAR ARCHIUVOS DENTRO DEL CONTENEDOR
COPY ./pom.xml /root
COPY ./.mvn /root/.mvn
COPY ./mvnw /root

#DESCARGAR LAS DEPENDENCIAS
RUN ./mvnw dependency:go-offline

#COPIAR EL CODIGO FUENTE DENTRO DEL CONTEDOR
COPY ./src /root/src

#CONSTRUIR NUSTRA APLICACION
RUN ./mvnw clean install -DskipTests

#LEVANTAR NUESTRA APLICACION CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java","-jar","/root/target/dualshare-0.0.1-SNAPSHOT.jar"]
